### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chb0github** [kurron/maven-publish-experiment#1]
Did you actually ever figure out publishing to Maven?

**Comment by kurron** [comment]
I did but I actually push to [Artifactory](https://www.jfrog.com/artifactory/).  For personal stuff, I publish to [Bintray](https://bintray.com/) using their plug-in.

**Comment by chb0github** [comment]
You mean maven central v artifactory? Yeah, I should have been clearer. I was looking to publish to artifactory too. I finally got it working. Been looking all over the net for working examples. Thanks for replying
